'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  ReactFlow,
  ReactFlowProvider,
  addEdge,
  useNodesState,
  useEdgesState,
  Background,
  BackgroundVariant,
  Controls,
  MiniMap,
  useReactFlow,
  type Connection,
  type Edge,
  type Node,
  type OnInit,
  type OnSelectionChangeParams,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import NodesPanel from './NodesPanel';
import ExecutionLogs from './ExecutionLogs';
import { customNodeTypes } from './nodes/CustomNodes';
import { nodeDefinitionByType } from './nodes/nodeTypes';
import {
  canvasToHookSchema,
  hookSchemaToCanvas,
  type HookConfig,
  type BuilderNodeData,
} from './hookSchema';
import { useExecutionEngine } from './useExecutionEngine';
import WorkflowChatPanel from './chat/WorkflowChatPanel';
import NodeConfigModal from './NodeConfigModal';
import WorkflowsDashboard from './WorkflowsDashboard';

// Node types that do NOT need the config popup (Flow / Decision control nodes)
const FLOW_TYPES = new Set(['start', 'end', 'ifCondition', 'wait', 'manualReview']);

interface CustomHook {
  id: string;
  hookName: string;
  category: string;
  functionName: string;
  moduleName: string;
  condition?: string;
  code: string;
}

const initialNodes: Node[] = [
  {
    id: 'start-1',
    type: 'start',
    position: { x: 320, y: 80 },
    data: { label: 'Start' },
  },
];

const initialEdges: Edge[] = [];

let nodeId = 0;
let edgeId = 0;

const getNodeId = () => `node-${++nodeId}`;
const getEdgeId = () => `edge-${++edgeId}`;

function WorkflowCanvas() {
  const reactFlowWrapper = useRef<HTMLDivElement>(null);
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);
  const [selectedNodeId, setSelectedNodeId] = useState<string | null>(null);
  const [configModalNodeId, setConfigModalNodeId] = useState<string | null>(null);
  const [clientCode, setClientCode] = useState('COGITATE');
  const [serializedSchema, setSerializedSchema] = useState('');
  const [message, setMessage] = useState<string | null>(null);
  const [isLibraryVisible, setIsLibraryVisible] = useState(true);
  const [isOverflowMenuOpen, setIsOverflowMenuOpen] = useState(false);
  
  // VS Code Bottom Panel State
  const [bottomPanelHeight, setBottomPanelHeight] = useState(40);
  const [lastExpandedHeight, setLastExpandedHeight] = useState(240);
  const [activeBottomTab, setActiveBottomTab] = useState<'logs' | 'schema'>('logs');
  const [isResizing, setIsResizing] = useState(false);
  // Floating AI Assistant State
  const [isChatOpen, setIsChatOpen] = useState(false);
  const [showSchema, setShowSchema] = useState(false);
  const [viewMode, setViewMode] = useState<'builder' | 'dashboard'>('builder');

  // Auto-dismiss toast messages after 2 seconds
  useEffect(() => {
    if (message) {
      const timer = setTimeout(() => setMessage(null), 2000);
      return () => clearTimeout(timer);
    }
  }, [message]);

  const autoGeneratedSchema = useMemo(() => {
    try {
      const schema = canvasToHookSchema(nodes, edges, clientCode);
      return JSON.stringify(schema, null, 2);
    } catch (err) {
      console.error('Schema auto-generation failed:', err);
      return '';
    }
  }, [nodes, edges, clientCode]);

  // Handle initialization for default zoom
  const onInit = useCallback<OnInit>((instance) => {
    instance.setViewport({ x: 0, y: 0, zoom: 0.6 });
  }, []);


  const { screenToFlowPosition, fitView } = useReactFlow();
  const [selectedEdgeId, setSelectedEdgeId] = useState<string | null>(null);
  const nodesRef = useCallback(() => nodes, [nodes]);
  const edgesRef = useCallback(() => edges, [edges]);
  const engine = useExecutionEngine(nodesRef, edgesRef);

  const isExecuting = engine.state === 'running' || engine.state === 'paused';

  const displayNodes = useMemo(() => {
    if (Object.keys(engine.nodeStatuses).length === 0) return nodes;

    return nodes.map((node) => {
      const status = engine.nodeStatuses[node.id];
      if (!status || status === 'idle') return node;
      return {
        ...node,
        data: { ...node.data, executionStatus: status },
      };
    });
  }, [nodes, engine.nodeStatuses]);

  const displayEdges = useMemo(() => {
    const hasEdgeExecutionState = Object.keys(engine.edgeStatuses).length > 0;

    return edges.map((edge) => {
      const execStatus = engine.edgeStatuses[edge.id];
      const branchLabel =
        edge.sourceHandle === 'yes' ? 'YES' : edge.sourceHandle === 'no' ? 'NO' : undefined;

      if (!hasEdgeExecutionState || !execStatus || execStatus === 'idle') {
        return {
          ...edge,
          label: branchLabel ?? edge.label,
          labelStyle: branchLabel
            ? { fontSize: 10, fontWeight: 600, fill: '#64748b' }
            : edge.labelStyle,
        };
      }

      if (execStatus === 'active') {
        return {
          ...edge,
          animated: true,
          style: { ...(edge.style ?? {}), stroke: '#16a34a', strokeWidth: 2.5 },
          className: `${edge.className ?? ''} edge-exec-active`.trim(),
          label: branchLabel ?? edge.label,
          labelStyle: { fontSize: 10, fontWeight: 600, fill: '#166534' },
        };
      }

      return {
        ...edge,
        animated: false,
        style: { ...(edge.style ?? {}), stroke: '#22c55e', strokeWidth: 2 },
        className: `${edge.className ?? ''} edge-exec-completed`.trim(),
        label: branchLabel ?? edge.label,
        labelStyle: { fontSize: 10, fontWeight: 600, fill: '#166534' },
      };
    });
  }, [edges, engine.edgeStatuses]);

  const selectedNode = useMemo(
    () => nodes.find((node) => node.id === selectedNodeId) ?? null,
    [nodes, selectedNodeId]
  );

  const onConnect = useCallback(
    (params: Connection) => {
      if (isExecuting) return;
      setEdges((currentEdges) =>
        addEdge(
          {
            ...params,
            id: getEdgeId(),
            type: 'smoothstep',
            animated: false,
            style: { stroke: '#cbd5e1', strokeWidth: 1.5 },
            markerEnd: { type: 'arrowclosed', color: '#94a3b8', width: 12, height: 12 },
          },
          currentEdges
        )
      );
    },
    [setEdges, isExecuting]
  );

  const onDragOver = useCallback(
    (event: React.DragEvent) => {
      if (isExecuting) return;
      event.preventDefault();
      event.dataTransfer.dropEffect = 'move';
    },
    [isExecuting]
  );

  const onDrop = useCallback(
    (event: React.DragEvent) => {
      if (isExecuting) return;
      event.preventDefault();

      const type = event.dataTransfer.getData('application/reactflow');
      if (!type) {
        return;
      }

      const position = screenToFlowPosition({
        x: event.clientX,
        y: event.clientY,
      });

      let node: Node;

      if (type.startsWith('customHook-')) {
        const hookPayload = event.dataTransfer.getData('application/reactflow-custom-hook');
        const hookData = hookPayload ? (JSON.parse(hookPayload) as CustomHook) : null;
        if (!hookData) return;

        node = {
          id: getNodeId(),
          type: 'customHook',
          position,
          data: {
            label: hookData.hookName,
            type: 'customHook',
            config: {
              FunctionName: hookData.functionName,
              ModuleName: hookData.moduleName,
              Condition: hookData.condition || '',
              code: hookData.code,
            },
            moduleName: hookData.moduleName,
            condition: hookData.condition,
            callFunction: true,
            isEndpoint: false,
          } as Node['data'],
        };
      } else {
        const definition = nodeDefinitionByType[type];
        node = {
          id: getNodeId(),
          type,
          position,
          data: {
            label: definition?.label ?? type,
            color: definition?.color,
            condition: definition?.defaultData?.condition,
            requestName: definition?.defaultData?.requestName,
            moduleName: definition?.defaultModuleName || undefined,
            isEndpoint: definition?.defaultData?.isEndpoint,
            callFunction: true,
            description: definition?.description,
          } satisfies BuilderNodeData,
        };
      }

      setNodes((currentNodes) => currentNodes.concat(node));
    },
    [screenToFlowPosition, setNodes, isExecuting]
  );

  const onSelectionChange = useCallback((params: OnSelectionChangeParams) => {
    const nodeId = params.nodes[0]?.id ?? null;
    setSelectedNodeId(nodeId);
    setSelectedEdgeId(params.edges[0]?.id ?? null);
  }, []);

  const onNodeDoubleClick = useCallback((_event: React.MouseEvent, node: Node) => {
    if (node && !FLOW_TYPES.has(node.type ?? '')) {
      setConfigModalNodeId(node.id);
    }
  }, []);

  const onDragStart = (event: React.DragEvent, nodeType: string, hookData?: CustomHook) => {
    event.dataTransfer.setData('application/reactflow', nodeType);
    if (hookData) {
      event.dataTransfer.setData(
        'application/reactflow-custom-hook',
        JSON.stringify(hookData)
      );
    }
    event.dataTransfer.effectAllowed = 'move';
  };

  const deleteSelection = useCallback(() => {
    if (isExecuting) return;

    if (selectedNodeId) {
      setNodes((currentNodes) => currentNodes.filter((node) => node.id !== selectedNodeId));
      setEdges((currentEdges) =>
        currentEdges.filter((edge) => edge.source !== selectedNodeId && edge.target !== selectedNodeId)
      );
      setSelectedNodeId(null);
      return;
    }

    if (selectedEdgeId) {
      setEdges((currentEdges) => currentEdges.filter((edge) => edge.id !== selectedEdgeId));
      setSelectedEdgeId(null);
    }
  }, [selectedEdgeId, selectedNodeId, setEdges, setNodes, isExecuting]);

  const clearCanvas = useCallback(() => {
    if (isExecuting) return;
    setNodes(initialNodes);
    setEdges(initialEdges);
    setSelectedNodeId(null);
    setSelectedEdgeId(null);
    setSerializedSchema('');
    setMessage('Canvas cleared.');
    engine.reset();
    setTimeout(() => fitView({ padding: 0.2 }), 50);
  }, [engine, fitView, isExecuting, setEdges, setNodes]);

  const updateNodeData = useCallback(
    (field: keyof BuilderNodeData, value: string | boolean | undefined) => {
      if (!selectedNodeId || isExecuting) return;

      setNodes((currentNodes) =>
        currentNodes.map((node) => {
          if (node.id !== selectedNodeId) return node;
          const data = (node.data ?? {}) as BuilderNodeData;
          return {
            ...node,
            data: { ...data, [field]: value } satisfies BuilderNodeData,
          };
        })
      );
    },
    [selectedNodeId, setNodes, isExecuting]
  );

  const saveNodeConfig = useCallback(
    (nodeId: string, patch: Partial<BuilderNodeData>) => {
      setNodes((currentNodes) =>
        currentNodes.map((node) => {
          if (node.id !== nodeId) return node;
          return { ...node, data: { ...node.data, ...patch } };
        })
      );
    },
    [setNodes]
  );

  const updateCondition = useCallback(
    (value: string) => updateNodeData('condition', value),
    [updateNodeData]
  );

  const exportSchema = useCallback(() => {
    const schema = canvasToHookSchema(nodes, edges, clientCode);
    setSerializedSchema(JSON.stringify(schema, null, 2));
    setShowSchema(true);
    setMessage('Hook schema generated from canvas.');
  }, [clientCode, edges, nodes]);

  const importSchema = useCallback(() => {
    if (isExecuting) return;
    try {
      const parsed = JSON.parse(serializedSchema || autoGeneratedSchema) as HookConfig;
      const restored = hookSchemaToCanvas(parsed);
      setNodes(restored.nodes);
      setEdges(restored.edges);
      setClientCode(parsed.Client || 'COGITATE');
      setSelectedNodeId(null);
      setSelectedEdgeId(null);
      setMessage('Canvas restored from hook schema.');
      setTimeout(() => fitView({ padding: 0.2 }), 50);
    } catch {
      setMessage('Invalid hook schema JSON. Please fix format and retry.');
    }
  }, [autoGeneratedSchema, fitView, serializedSchema, setEdges, setNodes, isExecuting]);

  const applyAISchema = useCallback((newSchema: HookConfig) => {
    if (isExecuting) return;
    try {
      const restored = hookSchemaToCanvas(newSchema);
      setNodes(restored.nodes);
      setEdges(restored.edges);
      setClientCode(newSchema.Client || 'COGITATE');
      setSelectedNodeId(null);
      setSelectedEdgeId(null);
      setMessage('Workflow updated by AI (HookConfig).');
      setTimeout(() => fitView({ padding: 0.2 }), 50);
    } catch (e) {
      console.error('Failed to apply AI HookConfig', e);
      setMessage('Failed to apply AI HookConfig. See console.');
    }
  }, [fitView, isExecuting, setEdges, setNodes]);

  const downloadSchema = useCallback(() => {
    const schema = canvasToHookSchema(nodes, edges, clientCode);
    const json = JSON.stringify(schema, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `hook-schema-${clientCode.toLowerCase()}.json`;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
    setMessage(`Downloaded hook-schema-${clientCode.toLowerCase()}.json`);
  }, [clientCode, edges, nodes]);

  const handleRun = useCallback(() => {
    engine.reset();
    if (bottomPanelHeight < 100) setBottomPanelHeight(240);
    setActiveBottomTab('logs');
    setTimeout(() => engine.run(), 50);
  }, [engine, bottomPanelHeight]);

  const handlePause = useCallback(() => {
    engine.pause();
  }, [engine]);

  const handleResume = useCallback(() => {
    engine.resume();
  }, [engine]);

  const handleStop = useCallback(() => {
    engine.stop();
  }, [engine]);

  const handleReset = useCallback(() => {
    engine.reset();
  }, [engine]);

  // Bottom Panel Resizing Logic
  const startResizing = useCallback(() => {
    setIsResizing(true);
    document.body.classList.add('resizing-n-s');
  }, []);

  const stopResizing = useCallback(() => {
    setIsResizing(false);
    document.body.classList.remove('resizing-n-s');
  }, []);

  const resize = useCallback((e: MouseEvent) => {
    if (isResizing) {
      const newHeight = window.innerHeight - e.clientY;
      // Min height: 40px (header), Max: 70% of viewport
      if (newHeight >= 40 && newHeight < window.innerHeight * 0.7) {
        setBottomPanelHeight(newHeight);
        if (newHeight > 45) {
          setLastExpandedHeight(newHeight);
        }
      }
    }
  }, [isResizing]);

  useMemo(() => {
    if (isResizing) {
      window.addEventListener('mousemove', resize);
      window.addEventListener('mouseup', stopResizing);
    } else {
      window.removeEventListener('mousemove', resize);
      window.removeEventListener('mouseup', stopResizing);
    }
    return () => {
      window.removeEventListener('mousemove', resize);
      window.removeEventListener('mouseup', stopResizing);
    };
  }, [isResizing, resize, stopResizing]);

  const selectedData = (selectedNode?.data ?? {}) as BuilderNodeData;
  const selectedCondition =
    typeof selectedData.condition === 'string'
      ? selectedData.condition
      : typeof selectedData.condition?.expression === 'string'
      ? selectedData.condition.expression
      : '';

  return (
    <div className="flex h-full w-full overflow-hidden bg-slate-50 font-sans text-slate-900">
      {/* ── Sidebar: Action Library ────────────────────── */}
      <NodesPanel 
        onDragStart={onDragStart} 
        isVisible={isLibraryVisible} 
        onToggle={() => setIsLibraryVisible((prev) => !prev)} 
      />

      {/* ── Main Workspace ────────────────────────────── */}
      <div className="relative flex flex-1 flex-col min-w-0 overflow-hidden">
        
        {/* Floating Open Library Button (when sidebar is closed) */}
        {!isLibraryVisible && (
          <button
            type="button"
            onClick={() => setIsLibraryVisible(true)}
            className="absolute left-6 top-6 z-50 flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200/60 bg-white/90 text-slate-500 shadow-sm backdrop-blur-sm transition-all hover:bg-slate-50 hover:text-slate-800 hover:shadow-md focus:outline-none"
            title="Open Library"
          >
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="h-5 w-5">
              <line x1="3" y1="12" x2="21" y2="12"></line>
              <line x1="3" y1="6" x2="21" y2="6"></line>
              <line x1="3" y1="18" x2="21" y2="18"></line>
            </svg>
          </button>
        )}

        {/* ── Top Toolbar ── */}
        <div className={`builder-toolbar shrink-0 items-center transition-all duration-300 ${!isLibraryVisible ? 'pl-28' : 'pl-4'}`}>
          <div className="flex items-center gap-6">
            <label className="flex items-center gap-3">
              <span className="text-[11px] font-bold text-slate-400 uppercase tracking-[0.15em] whitespace-nowrap">Client Code</span>
            <input
              value={clientCode}
              onChange={(event) => setClientCode(event.target.value)}
              className="toolbar-input"
              placeholder="e.g., COGITATE"
            />
            </label>
          </div>
          <div className="flex-1 px-4 flex justify-center">
            <div className="flex bg-slate-100 p-1 rounded-xl border border-slate-200 shadow-sm">
              <button
                onClick={() => setViewMode('builder')}
                className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${
                  viewMode === 'builder' 
                    ? 'bg-white text-blue-600 shadow-sm ring-1 ring-slate-200' 
                    : 'text-slate-500 hover:text-slate-800'
                }`}
              >
                Builder
              </button>
              <button
                onClick={() => setViewMode('dashboard')}
                className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${
                  viewMode === 'dashboard' 
                    ? 'bg-white text-blue-600 shadow-sm ring-1 ring-slate-200' 
                    : 'text-slate-500 hover:text-slate-800'
                }`}
              >
                Dashboard
              </button>
            </div>
          </div>

          {/* ─── Execution Controls ─── */}
          <div className="flex items-center gap-2 border-l border-slate-200 pl-4">
            {engine.state !== 'running' && engine.state !== 'paused' && (
              <button type="button" className="exec-btn exec-btn-run" onClick={handleRun}>
                ▶ Run
              </button>
            )}
            {engine.state === 'running' && (
              <button type="button" className="exec-btn exec-btn-pause" onClick={handlePause}>
                ⏸ Pause
              </button>
            )}
            {engine.state === 'paused' && (
              <button type="button" className="exec-btn exec-btn-run" onClick={handleResume}>
                ▶ Resume
              </button>
            )}
            {isExecuting && (
              <button type="button" className="exec-btn exec-btn-stop" onClick={handleStop}>
                ⏹ Stop
              </button>
            )}
            {(engine.state === 'completed' || engine.state === 'error') && (
              <button type="button" className="exec-btn exec-btn-reset" onClick={handleReset}>
                ↺ Reset
              </button>
            )}
          </div>

          <div className="h-5 w-px bg-slate-200 mx-2" />

          {/* ─── Overflow Actions Menu ─── */}
          <div className="relative">
            <button
              type="button"
              onClick={() => setIsOverflowMenuOpen((prev) => !prev)}
              className={`flex h-9 w-9 items-center justify-center rounded-lg border transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500/20 ${
                isOverflowMenuOpen
                  ? 'border-blue-200 bg-blue-50 text-blue-700'
                  : 'border-slate-200 bg-white text-slate-600 hover:bg-slate-50 hover:text-slate-900'
              }`}
              title="More Actions"
            >
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="h-5 w-5">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="12" cy="5" r="1"></circle>
                <circle cx="12" cy="19" r="1"></circle>
              </svg>
            </button>

            {isOverflowMenuOpen && (
              <>
                <div className="fixed inset-0 z-40" onClick={() => setIsOverflowMenuOpen(false)} />
                <div className="absolute right-0 top-[calc(100%+8px)] z-50 w-56 rounded-xl border border-slate-100 bg-white p-2 shadow-xl shadow-slate-200/50 flex flex-col gap-1">
                  
                  <div className="px-3 pb-1 pt-2 text-[10px] font-bold uppercase tracking-wider text-slate-400">
                    Canvas Controls
                  </div>
                  <button
                    type="button"
                    onClick={() => { fitView({ padding: 0.2 }); setIsOverflowMenuOpen(false); }}
                    className="flex w-full items-center gap-3 rounded-md px-3 py-2 text-left text-[13px] font-medium text-slate-700 transition-colors hover:bg-slate-50"
                  >
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="h-4 w-4"><path d="M15 3h6v6M9 21H3v-6M21 3l-7 7M3 21l7-7"></path></svg>
                    Fit View
                  </button>
                  <button
                    type="button"
                    onClick={() => { clearCanvas(); setIsOverflowMenuOpen(false); }}
                    className="flex w-full items-center gap-3 rounded-md px-3 py-2 text-left text-[13px] font-medium text-slate-700 transition-colors hover:bg-slate-50"
                  >
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="h-4 w-4"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="9" y1="9" x2="15" y2="15"></line><line x1="15" y1="9" x2="9" y2="15"></line></svg>
                    Clear Canvas
                  </button>
                  <button
                    type="button"
                    onClick={() => { deleteSelection(); setIsOverflowMenuOpen(false); }}
                    className="flex w-full items-center gap-3 rounded-md px-3 py-2 text-left text-[13px] font-medium text-red-600 transition-colors hover:bg-red-50"
                  >
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="h-4 w-4"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg>
                    Delete Selected
                  </button>
                </div>

              </>
            )}
          </div>
        </div>

        {/* ── Dashboard Area ── */}
        {viewMode === 'dashboard' ? (
          <div className="flex-1 overflow-hidden">
             <WorkflowsDashboard config={canvasToHookSchema(nodes, edges, clientCode)} />
          </div>
        ) : (
          /* ── Canvas Area ── */
          <div className="relative flex-1 min-h-0 overflow-hidden">
          <div className="absolute inset-0" ref={reactFlowWrapper}>
            <ReactFlow
              nodes={displayNodes}
              edges={displayEdges}
              onNodesChange={onNodesChange}
              onEdgesChange={onEdgesChange}
              onConnect={onConnect}
              onDragOver={onDragOver}
              onDrop={onDrop}
              onSelectionChange={onSelectionChange}
              onNodeDoubleClick={onNodeDoubleClick}
              onInit={onInit}
              nodeTypes={customNodeTypes}
              defaultViewport={{ x: 0, y: 0, zoom: 0.6 }}
              fitView={false} // Disable fitView to respect defaultViewport/onInit
              deleteKeyCode={['Delete', 'Backspace']}
            >
              <Background variant={BackgroundVariant.Dots} gap={20} color="#e2e8f0" />
              <Controls position="bottom-right" />
              <MiniMap 
                position="bottom-right" 
                style={{ 
                  borderRadius: '12px', 
                  overflow: 'hidden', 
                  border: '2px solid #f1f5f9',
                  bottom: '84px', // Space for AI button
                  right: '24px',
                  width: 150,
                  height: 100,
                  pointerEvents: 'auto',
                  zIndex: 90
                }} 
                zoomable 
                pannable 
                nodeStrokeColor={(n) => (n.type === 'start' ? '#22c55e' : '#cbd5e1')}
                nodeColor={(n) => (n.type === 'start' ? '#f0fdf4' : '#ffffff')}
                nodeBorderRadius={8}
              />
            </ReactFlow>
          </div>

          {/* Condition Editor (when ifCondition selected) */}
          {selectedNode?.type === 'ifCondition' && (
            <div className="absolute top-4 left-4 right-4 z-40">
              <div className="condition-panel rounded-2xl border border-amber-200/60 bg-white/95 p-4 shadow-xl backdrop-blur-md">
                <div className="flex flex-wrap items-end gap-4">
                  <label className="flex min-w-[200px] flex-1 flex-col gap-2 text-[11px] font-bold uppercase tracking-wider text-amber-900/60">
                    Condition expression
                    <input
                      className="toolbar-input w-full"
                      value={selectedCondition}
                      onChange={(event) => updateCondition(event.target.value)}
                      placeholder='e.g., Transaction.Type = "Quote" AND Amount > 1000'
                    />
                  </label>
                  <label className="flex min-w-[180px] flex-1 flex-col gap-2 text-[11px] font-bold uppercase tracking-wider text-amber-900/60">
                    Module name
                    <input
                      className="toolbar-input w-full"
                      value={selectedData.moduleName ?? ''}
                      onChange={(e) => updateNodeData('moduleName', e.target.value)}
                      placeholder="@cogitate/core-pos-components"
                    />
                  </label>
                </div>
              </div>
            </div>
          )}

          {/* Toast Message */}
          {message && (
            <div className="absolute bottom-6 left-1/2 -translate-x-1/2 z-50">
              <span className="flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-5 py-2 text-sm font-semibold text-emerald-700 shadow-xl shadow-emerald-100/40 animate-in fade-in slide-in-from-bottom-4">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="h-4 w-4"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg>
                {message}
              </span>
            </div>
          )}
        </div>
        )}

        {/* ── VS Code Style Resizable Bottom Panel ── */}
        <div 
          className={`shrink-0 flex flex-col bg-[#0f1419] border-t border-slate-800 ${isResizing ? '' : 'transition-[height] duration-200 ease-out'}`}
          style={{ height: `${bottomPanelHeight}px` }}
        >
          {/* Resize Handle Container */}
          <div 
            className="group absolute -top-1 left-0 right-0 z-[60] h-2 cursor-ns-resize"
            onMouseDown={startResizing}
          >
            {/* Visual feedback line + Arrows */}
            <div className="absolute top-1 left-0 right-0 h-0.5 bg-blue-500 opacity-0 group-hover:opacity-100 transition-opacity" />
            <div className="absolute -top-3 left-1/2 -translate-x-1/2 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
              <span className="bg-blue-500 text-white text-[10px] px-1.5 py-0.5 rounded shadow-lg font-bold">↕</span>
            </div>
          </div>

          {/* Panel Header / Tabs */}
          <div className="flex h-10 items-center justify-between px-4 border-b border-white/[0.05] shrink-0">
            <div className="flex items-center gap-6 h-full">
              {(['logs', 'schema'] as const).map((tab) => (
                <button
                  key={tab}
                  type="button"
                  onClick={() => {
                    setActiveBottomTab(tab);
                    if (bottomPanelHeight <= 45) {
                      setBottomPanelHeight(lastExpandedHeight);
                    }
                  }}
                  className={`relative h-full text-[11px] font-bold uppercase tracking-widest transition-colors ${
                    bottomPanelHeight > 45 && activeBottomTab === tab ? 'text-white' : 'text-slate-500 hover:text-slate-300'
                  }`}
                >
                  {tab === 'logs' ? 'Execution Logs' : 'Schema'}
                  {bottomPanelHeight > 45 && activeBottomTab === tab && (
                    <span className="absolute bottom-0 left-0 right-0 h-[2px] bg-blue-500" />
                  )}
                </button>
              ))}
            </div>

            <div className="flex items-center gap-3">
              <button
                type="button"
                onClick={() => setBottomPanelHeight(40)}
                className="flex h-6 w-6 items-center justify-center rounded hover:bg-white/10 text-slate-500 transition-colors"
                title="Minimize Panel"
              >
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="h-4 w-4">
                  <line x1="18" y1="6" x2="6" y2="18"></line>
                  <line x1="6" y1="6" x2="18" y2="18"></line>
                </svg>
              </button>
            </div>
          </div>


          {/* Panel Content (Independent Scroll) */}
          {bottomPanelHeight > 45 && (
            <div className="flex-1 min-h-0 relative">
              {activeBottomTab === 'logs' && (
                <div className="absolute inset-0 overflow-y-auto custom-scrollbar">
                  <ExecutionLogs 
                    logs={engine.logs} 
                    executionState={engine.state} 
                    progress={engine.progress} 
                    onClear={handleReset} 
                  />
                </div>
              )}
              
              {activeBottomTab === 'schema' && (
                <div className="h-full flex flex-col p-4">
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex flex-col gap-0.5">
                      <label className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-500">
                        Workflow Schema
                      </label>
                      <span className="text-[9px] text-slate-600 font-medium tracking-tight">
                        Schema is automatically generated based on your workflow.
                      </span>
                    </div>
                    
                    <div className="flex items-center gap-4">
                      <div className="flex rounded-xl overflow-hidden border border-white/10 shadow-2xl bg-[#1a1f26]">
                        <button
                          onClick={exportSchema}
                          className="px-20 py-2.5 text-[12px] font-bold uppercase text-slate-200 hover:text-white hover:bg-white/5 transition-all border-r border-white/10"
                        >
                          Export
                        </button>
                        <button
                          onClick={importSchema}
                          className="px-20 py-2.5 text-[12px] font-bold uppercase text-slate-200 hover:text-white hover:bg-white/5 transition-all border-r border-white/10"
                        >
                          Import
                        </button>
                        <button
                          onClick={downloadSchema}
                          className="px-20 py-2.5 text-[12px] font-bold uppercase text-slate-200 hover:text-white hover:bg-white/5 transition-all"
                        >
                          Download
                        </button>
                      </div>
                    </div>
                  </div>
                  {showSchema ? (
                    <textarea
                      onChange={(e) => setSerializedSchema(e.target.value)}
                      className="flex-1 w-full font-mono text-[13px] p-4 rounded-xl border border-white/[0.03] outline-none resize-none transition-all custom-scrollbar bg-[#0a0d11]/50 text-emerald-400/80 focus:border-emerald-500/20"
                      value={serializedSchema || autoGeneratedSchema}
                    />
                  ) : (
                    <div className="flex-1 flex items-center justify-center border border-dashed border-white/5 rounded-xl bg-white/[0.02]">
                      <p className="text-slate-500 text-[13px] font-medium tracking-tight">Click &quot;Export&quot; to generate schema</p>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

        </div>

        {/* ── Floating AI Assistant ── */}
        <div className="fixed bottom-6 right-6 z-[100] flex flex-col items-end gap-4">
          {/* Chat Panel (Slide-in right) */}
          {isChatOpen && (
            <div className="w-[420px] h-[600px] max-h-[calc(100vh-120px)] bg-white rounded-3xl shadow-2xl border border-slate-200 flex flex-col overflow-hidden animate-in slide-in-from-right-8 duration-300">
              <div className="flex items-center justify-between px-6 py-4 bg-slate-50 border-b border-slate-200">
                <div className="flex items-center gap-3">
                  <div className="h-8 w-8 rounded-full bg-indigo-600 flex items-center justify-center text-white font-bold">AI</div>
                  <h3 className="font-bold text-slate-800">Workflow Designer</h3>
                </div>
                <button 
                  onClick={() => setIsChatOpen(false)}
                  className="text-slate-400 hover:text-slate-600"
                >
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="h-5 w-5"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
                </button>
              </div>
              <div className="flex-1 min-h-0">
                <WorkflowChatPanel 
                  currentSchema={canvasToHookSchema(nodes, edges, clientCode)}
                  onApplySchema={applyAISchema} 
                />
              </div>
            </div>
          )}

          {/* Floating Toggle Button (Square AI Label) */}
          <button
            type="button"
            onClick={() => setIsChatOpen(!isChatOpen)}
            className={`flex h-12 w-12 items-center justify-center rounded-xl shadow-2xl transition-all duration-300 transform hover:scale-105 active:scale-95 border ${
              isChatOpen ? 'bg-slate-800 text-white border-slate-700' : 'bg-white text-indigo-600 border-indigo-100 hover:border-indigo-200'
            }`}
          >
            <span className="text-[15px] font-black tracking-tight">{isChatOpen ? '✕' : 'AI'}</span>
          </button>
        </div>

      </div>

      {/* Node Configuration Modal */}
      {configModalNodeId && (
        <NodeConfigModal
          nodeLabel={(nodes.find((n) => n.id === configModalNodeId)?.data?.label as string) || 'Target Action'}
          initialData={(nodes.find((n) => n.id === configModalNodeId)?.data as BuilderNodeData) || {}}
          onClose={() => setConfigModalNodeId(null)}
          onSave={(patch) => {
            saveNodeConfig(configModalNodeId, patch);
            setConfigModalNodeId(null);
          }}
        />
      )}
    </div>
  );
}

export default function WorkflowBuilder() {
  return (
    <ReactFlowProvider>
      <WorkflowCanvas />
    </ReactFlowProvider>
  );
}
