export type ActionCategory = 'Flow' | 'Decision' | 'Pre Hook' | 'Post Hook';

export interface NodeDefinition {
  type: string;
  label: string;
  icon: string;
  color: string;
  category: ActionCategory;
  functionName: string;
  defaultModuleName: string;
  description: string;
  defaultData?: {
    condition?: string;
    isEndpoint?: boolean;
    requestName?: string;
  };
}

export const nodeDefinitions: NodeDefinition[] = [
  // ─── Flow Nodes ─────────────────────────────────────────
  {
    type: 'start',
    label: 'Start',
    icon: 'ST',
    color: '#16a34a',
    category: 'Flow',
    functionName: 'Start',
    defaultModuleName: '',
    description: 'Entry point of the workflow',
  },
  {
    type: 'end',
    label: 'End',
    icon: 'EN',
    color: '#dc2626',
    category: 'Flow',
    functionName: 'End',
    defaultModuleName: '',
    description: 'Exit point of the workflow',
  },
  {
    type: 'wait',
    label: 'Wait for Time',
    icon: 'WT',
    color: '#0ea5e9',
    category: 'Flow',
    functionName: 'WaitForTime',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Pauses execution for a configured duration',
  },
  {
    type: 'manualReview',
    label: 'Send to Manual Review',
    icon: 'MR',
    color: '#475569',
    category: 'Flow',
    functionName: 'SendToManualReview',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Routes the transaction for human review',
  },

  // ─── Decision Nodes ─────────────────────────────────────
  {
    type: 'ifCondition',
    label: 'If / Else',
    icon: 'IF',
    color: '#d97706',
    category: 'Decision',
    functionName: 'EvaluateCondition',
    defaultModuleName: '',
    description: 'Conditional branching based on an expression',
    defaultData: { condition: "Transaction.Type = 'Application'" },
  },

  // ─── Pre Hook Nodes (from Hooks-Action-Function-Struture.json) ──
  {
    type: 'generateQuoteNumber',
    label: 'Generate Quote Number',
    icon: 'QN',
    color: '#2563eb',
    category: 'Pre Hook',
    functionName: 'GenerateQuoteNumber',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Generates or updates a quote number from product master',
    defaultData: { requestName: '/Quote/Landing' },
  },
  {
    type: 'getGeoCodeAddress',
    label: 'Geocode Address',
    icon: 'GC',
    color: '#0891b2',
    category: 'Pre Hook',
    functionName: 'getGeoCodeAddressHook',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Fetches geocoding information for addresses using Google Maps API',
    defaultData: { requestName: '/Quote/Landing' },
  },
  {
    type: 'executeUnderwritingRules',
    label: 'Execute Underwriting Rules',
    icon: 'UW',
    color: '#6366f1',
    category: 'Pre Hook',
    functionName: 'ExecuteUnderwritingRules',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Executes underwriting rules against the policy model',
    defaultData: { requestName: '/Quote/Summary' },
  },
  {
    type: 'getRatingFromThirdParty',
    label: 'Get Third-Party Rating',
    icon: 'TR',
    color: '#7c3aed',
    category: 'Pre Hook',
    functionName: 'getRatingFromThirdParty',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Invokes a third-party rater to get policy rating',
    defaultData: { requestName: '/Quote/Summary' },
  },
  {
    type: 'invokeMultipleRaters',
    label: 'Invoke Multiple Raters',
    icon: 'MR',
    color: '#8b5cf6',
    category: 'Pre Hook',
    functionName: 'invokeMultipleRaters',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Runs multiple raters concurrently and returns consolidated results',
    defaultData: { requestName: '/Quote/Summary' },
  },
  {
    type: 'getRaterKey',
    label: 'Get Rater Key',
    icon: 'RK',
    color: '#4f46e5',
    category: 'Pre Hook',
    functionName: 'getRaterKeyFromProductMaster',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Retrieves the rater key for a product from master configuration',
    defaultData: { requestName: '/Quote/Summary' },
  },
  {
    type: 'startTransaction',
    label: 'Start Transaction',
    icon: 'TX',
    color: '#1d4ed8',
    category: 'Pre Hook',
    functionName: 'startTransaction',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Initiates a new transaction, handles OOT scenarios and pending states',
  },
  {
    type: 'createNewQuoteVersion',
    label: 'Create Quote Version',
    icon: 'QV',
    color: '#1e40af',
    category: 'Pre Hook',
    functionName: 'createNewQuoteVersion',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Creates a new version of a quote for endorsements or amendments',
  },
  {
    type: 'getAIMInsuredId',
    label: 'Get AIM Insured ID',
    icon: 'AI',
    color: '#0e7490',
    category: 'Pre Hook',
    functionName: 'getAIMInsuredId',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Fetches AIM Insured ID from external API and updates external references',
  },
  {
    type: 'getAIMSubmissionId',
    label: 'Get AIM Submission ID',
    icon: 'AS',
    color: '#0369a1',
    category: 'Pre Hook',
    functionName: 'getAIMSubmissionId',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Fetches AIM Quote ID from external API',
  },
  {
    type: 'summaryOOS',
    label: 'Summary OOS',
    icon: 'OS',
    color: '#3b82f6',
    category: 'Pre Hook',
    functionName: 'summaryOOS',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Generates Out-of-Sequence summary with conflict detection',
  },
  {
    type: 'processOOS',
    label: 'Process OOS',
    icon: 'PO',
    color: '#2563eb',
    category: 'Pre Hook',
    functionName: 'processOOS',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Processes Out-of-Sequence policy transactions',
  },
  {
    type: 'reinstatementUtilities',
    label: 'Reinstatement Utilities',
    icon: 'RI',
    color: '#1e3a5f',
    category: 'Pre Hook',
    functionName: 'ReinstatementUtilities',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Handles policy reinstatement workflow including rating and binding',
  },

  // ─── Post Hook Nodes (from Hooks-Action-Function-Struture.json) ──
  {
    type: 'publishEvent',
    label: 'Publish Event',
    icon: 'PE',
    color: '#be185d',
    category: 'Post Hook',
    functionName: 'PublishEvent',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Publishes a policy event to the event system for lifecycle tracking',
    defaultData: { requestName: '/Application/Summary' },
  },
  {
    type: 'generateForms',
    label: 'Generate Forms',
    icon: 'GF',
    color: '#db2777',
    category: 'Post Hook',
    functionName: 'generateForms',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Generates forms by queuing an async web job',
    defaultData: { requestName: '/Application/Summary' },
  },
  {
    type: 'generateFormsDraft',
    label: 'Generate Forms Draft',
    icon: 'FD',
    color: '#ec4899',
    category: 'Post Hook',
    functionName: 'generateFormsDraft',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Generates draft forms for a policy transaction',
    defaultData: { requestName: '/Quote/Summary' },
  },
  {
    type: 'getEmailTemplateBody',
    label: 'Get Email Template',
    icon: 'EM',
    color: '#dc2626',
    category: 'Post Hook',
    functionName: 'getEmailTemplateBody',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Retrieves and returns the email template body for notification',
    defaultData: { requestName: '/Application/Summary' },
  },
  {
    type: 'copyDocuments',
    label: 'Copy Documents',
    icon: 'CD',
    color: '#f43f5e',
    category: 'Post Hook',
    functionName: 'copyDocuments',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Copies documents from source to destination via DMS API',
    defaultData: { requestName: '/Application/Summary' },
  },
  {
    type: 'invokeAdaptiveAPI',
    label: 'Invoke Adaptive API',
    icon: 'AA',
    color: '#9f1239',
    category: 'Post Hook',
    functionName: 'invokeAdaptiveAPI',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Invokes the Adaptive Form API to process policy documents',
    defaultData: { isEndpoint: true },
  },
  {
    type: 'executeAdaptiveApiRequest',
    label: 'Execute Adaptive API',
    icon: 'EA',
    color: '#881337',
    category: 'Post Hook',
    functionName: 'executeAdaptiveApiRequest',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Executes an Adaptive Form API request with policy data',
    defaultData: { isEndpoint: true },
  },
  {
    type: 'deleteQuoteVersionsOnBind',
    label: 'Delete Quote Versions',
    icon: 'DV',
    color: '#14b8a6',
    category: 'Post Hook',
    functionName: 'deleteQuoteVersionsOnBind',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Deletes intermediate quote versions when a quote is bound',
    defaultData: { requestName: '/Application/Summary' },
  },
  {
    type: 'getMarkelForms',
    label: 'Get Markel Forms',
    icon: 'MF',
    color: '#0d9488',
    category: 'Post Hook',
    functionName: 'getMarkelForms',
    defaultModuleName: '@cogitate/core-pos-components',
    description: 'Retrieves forms from Markel rater response',
    defaultData: { requestName: '/Quote/Summary' },
  },
];

export const nodeDefinitionByType = Object.fromEntries(
  nodeDefinitions.map((definition) => [definition.type, definition])
) as Record<string, NodeDefinition>;
